# -*- coding: utf-8 -*-
"""New York Housing Market LR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tJKEq23xdSeAdxxemw0k6umC-QBqMHnv
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import streamlit as st
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# %matplotlib inline

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

df = pd.read_csv('NY-House-Dataset.csv')

df = df[df["PRICE"] < 1000000]

quant_df = df.select_dtypes(include = [np.number])

X = quant_df[['BEDS', 'BATH', 'PROPERTYSQFT']]
y = quant_df['PRICE']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

lr = LinearRegression()
lr.fit(X_train, y_train)

pred = lr.predict(X_test)

feature_names = [f'Feature_{i}' for i in list(X.columns)]

df_X = pd.DataFrame(X, columns = feature_names)

coefficients = lr.coef_

importance = np.abs(coefficients)

plt.figure(figsize=(10, 8))
plt.barh(feature_names, importance)
plt.xlabel('Importance')
plt.ylabel('Feature Names')
plt.title('Feature Importance')

from sklearn import metrics
from sklearn.metrics import r2_score


# Streamlit Code

st.image('statue_of_liberty.jpg', width=100)

st.title("NY Housing Market Linear Regression")

MAE = metrics.mean_absolute_error(y_test, pred)
MSE = metrics.mean_squared_error(y_test, pred)
r2val = r2_score(y_test,pred,multioutput='variance_weighted')

st.metric(label = "Mean Absolute Error", value = f"${MAE}")
st.metric(label = "Mean Squared Error", value = f"${MSE}")
st.metric(label = "R-Squared", value = r2val)

st.dataframe(quant_df.head(10))

st.pyplot(plt)


st.scatter_chart(data = df, x = "MAIN_ADDRESS", y = "PRICE")

st.bar_chart(data = df, x = "MAIN_ADDRESS", y = "PROPERTYSQFT")
